Update check_singbox.yml

diff --git a/.github/workflows/check_singbox.yml b/.github/workflows/check_singbox.yml
--- a/.github/workflows/check_singbox.yml
+++ b/.github/workflows/check_singbox.yml
@@ -21,8 +21,11 @@ jobs:
 
     - name: Install dependencies
       run: |
-        python -m pip install --upgrade pip
+        python3 -m pip install --upgrade pip
         pip install requests
+
+    - name: Install sshpass
+      run: sudo apt-get install sshpass
 
     - name: Debug environment variables
       run: |
@@ -36,4 +39,4 @@ jobs:
         TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
         TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
       run: |
-        python recover_singbox.py || { echo 'Python script failed'; exit 1; }
+        python3 recover_singbox.py || { echo 'Python script failed'; exit 1; }
